const string_resources = {
    SNO: "학수번호",
    SUBJECT: "과목이름",
    DEPARTMENT: "학과",
    GRADE: "학년",
    CREDIT: "학점",
    CATEGORY: "분류",
    TIME: "시간",
    PLACE: "장소",
    PROFESSOR: "교수이름",
    RATE: "평가",
    REMARK: "비고",
    NO_RESULT_OF_CONDITION: "조건에 해당하는 결과가 없습니다.",
    SELECT_SUBJECT: "과목 선택",
    SELECT_THE_CLASS: "해당 분반만 선택",
    IS_REQUIRED: "필수 여부",
    NO_RESULT_OF_CONDITION_TIMETABLE_VIEW: "조건에 맞는 시간표가 하나도 없어요...",
    PLEASE_CONFIRM: "필수 분반끼리 시간이 겹치는지 한번 확인해주세요..",
    SORT_CONDITIONL: "정렬기준",
    SUM_CREDIT: "총 학점",
    SUM_TIME: "총 수업시간",
    LONGEST_CONTINUOUS_CLASS:"최장 연강",
    DAY: "수업일수",
    MORE_INFO: "과목과 교시에 마우스 커서를 올리시면 더 자세한 정보를 확인할 수 있습니다.",
    CANNOT_SEE_ONE_VIEW: "표가 한 화면에 보이지 않으면 Ctrl +, -로 조정하세요",
    TOO_MANY_TIMETABLES: "경우의 수가 너무 많으면 최소학점/최대학점을 조절해보세요",
};

export default string_resources